title: Roman Martyrology
name: Roman Martyrology 
author: Veronica Brandt
#url: http://localhost:4000
#url: http://www.brandt.id.au/roman-martyrology
url: http://veromary.github.com/roman-martyrology
#baseurl: roman-martyrology/

collections:
  martyrs:
    output: true
  textonly:
    output: true

email: veroicon@gmail.com

google_analytics: UA-39801667-1
